### ISSUE TITLE
genericHTML scripts do not run

### ISSUE THREAD

**Issue by jme-s** [lakshaykaushik/PublishHTMLReport#14]
It seems that because the Generic HTML page is loaded as the body of the JMeter template rather than being displayed as its own page, scripts are not running.
Rather than adding the GenericHTML as the body to the JMeter page, can you just display the HTML without the JMeter page as its parent?

**Comment by lakshaykaushik** [comment]
This is happening because as per html5, inline appended scripts using innerHTML are not executed when page is loaded. This can be solved by doing appendChild on individual script tags, so basically if you have script tags in your html, we can fetch them and then use appendChild during rendering. 

Is this blocking you? If yes, i can spend some time and solve this. If you understand the code base, i would also be happy to receive a PR which solves this (fetching scripts and using appendChild). Let me know.

**Comment by jme-s** [comment]
Thanks for coming back to me. There are a lot of features in the html report we are generating (table sorting, search, theming etc) that aren't currently working because of this. 
I do not understand your code base enough to contribute anything meaningful, so would appreciate any work you can do to resolve this. 
I'm fairly certain your plugin will become quite popular for the Generic HTML feature as well as JMeter so this would a great enhancement for all.

**Comment by PrateekChauhan0194** [comment]
I was facing the same issue. But it turned out to be the path issue.
The way this extension works is that it expects the path to the `*.html` file. 
I was facing this issue when was giving the directory path (ex: _./directoryPath_) in the `htmlPath` parameter.
It turned out that it doesn't pick the `index.html` in the given directory path by itself.
The moment I changed the value to the `index.html` (ex: _./directoryPath/index.html_), it started working.

<img width="1414" alt="Screen Shot 2021-02-11 at 12 06 04 am" src="https://user-images.githubusercontent.com/68464629/107514014-29f8c800-6bfd-11eb-8ba3-95858006554a.png">

I hope this helps. :)

**Comment by jme-s** [comment]
> The moment I changed the value to the `index.html` (ex: _./directoryPath/index.html_), it started working.

Hmm interesting. Is your setup also using the genericHTML HTMLType? I already had the .html set and it doesn't work for me.

![image](https://user-images.githubusercontent.com/52516184/107565722-d9a75780-6c48-11eb-9130-180e9f2ca005.png)

**Comment by PrateekChauhan0194** [comment]
> > The moment I changed the value to the `index.html` (ex: _./directoryPath/index.html_), it started working.
> 
> Hmm interesting. Is your setup also using the genericHTML HTMLType? I already had the .html set and it doesn't work for me.
> 
> ![image](https://user-images.githubusercontent.com/52516184/107565722-d9a75780-6c48-11eb-9130-180e9f2ca005.png)

Yes, it's `genericHTML`.
Would you mind sharing a screenshot of the step defined in your `azure-pipelines.yml` file?

**Comment by woscostametaxa** [comment]
I think my current problem should fit into that issue:

I create a DoxyGen report and would like to publish it to the build - if I understand your initial comment correctly this is a problem of how HTML5 works or should that possibly work already?

I am uncertain in this regard and to be honest not all that aware in HTML features.

**Comment by czarls** [comment]
Hi all! I'm actually facing very similar issue. My tests publish HTML report generated by SpecflowRunner. I pass the correct path to this file, set the htmlType as "genericHTML" and task pass with no issues but published HTML report is still empty for some reason and has JMeter template. As someone here said, it would be great to simply publish that html file. Any suggestions for my case?

**Comment by tranquvis** [comment]
Hi,

I think I have the same problem with the robot framework report. As you can see in the image javascript seems to be not executed. 
![image](https://user-images.githubusercontent.com/8074528/111439174-63918700-8705-11eb-80de-a3b6dc704b45.png)

> @jme-s: I'm fairly certain your plugin will become quite popular for the Generic HTML feature as well as JMeter so this would a great enhancement for all.

I agree. Displaying a generic html is a very simple but often very useful feature and there is only one alternative at the moment: https://github.com/JakubRumpca/azure-pipeline-html-report. I didn't try it yet.

> @lakshaykaushik: This is happening because as per html5, inline appended scripts using innerHTML are not executed when page is loaded. This can be solved by doing appendChild on individual script tags, so basically if you have script tags in your html, we can fetch them and then use appendChild during rendering.

Seems to be a quite easy fix, but I don't understand why the page is embedded inside the JMeter template. This also causes delay and sometimes the JMeter UI is visible for a second.

**Comment by lakshaykaushik** [comment]
Robot framework will not work out of the box.
It is a separate issue

**Comment by lakshaykaushik** [comment]
Can you attach robot framework report with this issue.

**Comment by tranquvis** [comment]
Here is an example report: http://robotframework.org/QuickStartGuide/report.html

**Comment by lakshaykaushik** [comment]
Robot framework is not supported. No plans in near future
